---
title: "Ecological Analysis Phylogenetic Tree"
output: html_notebook
---

```{r load packages}
library(phytools)
library(psych)
library(GPArotation)
library(corpcor)
library(ape)
library(brms)
library(geiger)
library(mice)
library(tidyverse)
library(reshape2)
library(ggridges)
library(bayesplot)
library(hexbin)
```

```{r load tree and data}
full_data <- readRDS("~/Desktop/Menstrual taboos/R CODE DATA FILES (USE)/full_data.rds")
phylo <- read.nexus("~/Desktop/Menstrual taboos/R CODE DATA FILES (USE)/Time-calibrated SCCS supertree ultrametric.nex")
```

```{r clean tree}
MT_Tree <- drop.tip(phylo, tip=c("Abipon", "Abkhaz", "Ajie", "Atayal", "Aweikoma", "Banen", "Basseri", "Bogo", "Cayua", "Fur_Darfur", "Gheg_Albanians", "Haitians", "Hausa", "Hebrews", "Ifugao", "Khalka_Mongols", "Konso", "Lamet", "Mao", "Mbau_Fijians", "MISSING_Botocudo", "MISSING_Kafa_Kaffa", "MISSING_Kutenai", "MISSING_Natchez", "MISSING_Timbira", "MISSING_Twana", "Mundurucu", "Negri_Sembilan", "New_Ireland", "Nicobarese", "Orokaiva", "Palauans", "Pentecost", "Popoluca", "Punjabi_West", "Rhade", "Russians", "Shilluk", "Suku", "Tobelorese", "Turks",  "Uttar_Pradesh"))
phylo.Reduced <- MT_Tree
phylo.reduced <- vcv.phylo(phylo.Reduced, cor=TRUE)
phylo_vcv <- vcv.phylo(phylo, cor=TRUE)
```

```{r save tree}
saveRDS(phylo.Reduced, "~/Desktop/Menstrual taboos/R CODE DATA FILES (USE)/phylo_reduced.rds")
saveRDS(phylo.reduced, "~/Desktop/Menstrual taboos/R CODE DATA FILES (USE)/phylo_vcv.rds")
saveRDS(phylo_vcv, "~/Desktop/Menstrual taboos/R CODE DATA FILES (USE)/phylo_vcv_all.rds")
```
